# This is used for country/character assignments, not the one in mcmun.constants

COUNTRIES_CHARACTER = (
    ('Countries', (
       ('AF', u'Afghanistan'), ('AL', u'Albania'), ('AC', u'ALECSO'),('DZ', u'Algeria'), 
	('AD', u'Andorra'), ('AO', u'Angola'), 
	('AG', u'Antigua and Barbuda'), ('AR', u'Argentina'), ('AM', u'Armenia'), 
	('AU', u'Australia'), 
	('AT', u'Austria'), ('AZ', u'Azerbaijan'), ('BS', u'Bahamas'), 
	('BH', u'Bahrain'), ('BD', u'Bangladesh'), ('BB', u'Barbados'), 
	('BY', u'Belarus'), ('BE', u'Belgium'), ('BZ', u'Belize'), 
	('BJ', u'Benin'), ('BT', u'Bhutan'), 
	('BO', u'Bolivia, Plurinational State of'), 
	('BA', u'Bosnia and Herzegovina'), ('BW', u'Botswana'), 
	('BR', u'Brazil'), ('BN', u'Brunei Darussalam'), ('BG', u'Bulgaria'), 
	('BF', u'Burkina Faso'), ('BI', u'Burundi'), ('KH', u'Cambodia'), 
	('CM', u'Cameroon'), ('CA', u'Canada'), ('CV', u'Cape Verde'), 
	('TD', u'Chad'), 
	('CL', u'Chile'), ('CN', u'China'), ('CO', u'Colombia'), ('KM', u'Comoros'), 
	('CG', u'Congo'), ('CR', u'Costa Rica'), ('CI', u"C\xf4te D'ivoire"), ('HR', u'Croatia'), 
	('CU', u'Cuba'), ('CY', u'Cyprus'), 
	('CZ', u'Czech Republic'), ('KP', u"Democratic People's Republic of Korea"),
	('RC', u'Democratic Republic of Congo'), ('DK', u'Denmark'), 
	('DJ', u'Djibouti'), ('DO', u'Dominican Republic'), 
	('EC', u'Ecuador'), ('EG', u'Egypt'), ('SV', u'El Salvador'), 
	('GQ', u'Equatorial Guinea'), ('ER', u'Eritrea'),
	('ET', u'Ethiopia'), ('FJ', u'Fiji'), ('FI', u'Finland'), 
	('FR', u'France'), ('GA', u'Gabon'), ('GM', u'Gambia'), 
	('GE', u'Georgia'), ('DE', u'Germany'), ('GH', u'Ghana'), 
	('GR', u'Greece'), ('GD', u'Grenada'), ('GT', u'Guatemala'), 
	('GN', u'Guinea'), ('GY', u'Guyana'), ('HT', u'Haiti'), 
	('HN', u'Honduras'), ('HU', u'Hungary'), 
	('IS', u'Iceland'), ('IN', u'India'), ('ID', u'Indonesia'),
	('IM', u'International Organization for Migration'),
	('IR', u'Iran, Islamic Republic of'), ('IQ', u'Iraq'), ('IE', u'Ireland'), 
	('IL', u'Israel'), ('IT', u'Italy'), ('JM', u'Jamaica'), ('JP', u'Japan'), 
	('JO', u'Jordan'), ('KZ', u'Kazakhstan'), ('KE', u'Kenya'), 
	('KW', u'Kuwait'), ('KG', u'Kyrgyzstan'), 
	('LA', u"Lao People's Democratic Republic"), ('LB', u'Lebanon'), 
	('LS', u'Lesotho'), ('LR', u'Liberia'), ('LY', u'Libya'), 
	('LT', u'Lithuania'), ('LU', u'Luxembourg'), 
	('MG', u'Madagascar'), 
	('MW', u'Malawi'), ('MY', u'Malaysia'), ('MV', u'Maldives'), 
	('ML', u'Mali'), ('MT', u'Malta'), ('MR', u'Mauritania'), 
	('MU', u'Mauritius'), ('MX', u'Mexico'), ('MC', u'Monaco'), 
	('MN', u'Mongolia'), ('MA', u'Morocco'), ('MZ', u'Mozambique'), 
	('MM', u'Myanmar'), ('NA', u'Namibia'),
	('NP', u'Nepal'), ('NL', u'Netherlands'),
	('NZ', u'New Zealand'), ('NI', u'Nicaragua'), ('NE', u'Niger'), 
	('NG', u'Nigeria'), ('NO', u'Norway'), 
	('OM', u'Oman'), ('IC', u'Organization of the Islamic Cooperation'), ('PK', u'Pakistan'), 
	('PS', u'Palestine'), ('PA', u'Panama'), 
	('PG', u'Papua New Guinea'), ('PY', u'Paraguay'), ('PE', u'Peru'), ('PH', u'Philippines'), 
	('PL', u'Poland'), ('PT', u'Portugal'), ('QA', u'Qatar'), 
	('KR', u'Republic of Korea'), ('MD', u'Republic of Macedonia'), 
	('RO', u'Romania'), ('RU', u'Russian Federation'), 
	('RW', u'Rwanda'), ('SR', u'Sahrawi Republic'), 
	('KN', u'Saint Kitts and Nevis'), ('LC', u'Saint Lucia'), 
	('VC', u'Saint Vincent and the Grenadines'), ('ST', u'Sao Tome and Principe'), 
	('SA', u'Saudi Arabia'), ('SN', u'Senegal'), 
	('RS', u'Serbia'), ('SC', u'Seychelles'), ('SL', u'Sierra Leone'), 
	('SG', u'Singapore'), ('SK', u'Slovakia'), ('SO', u'Somalia'), ('ZA', u'South Africa'), 
	('SS', u'South Sudan'), 
	('ES', u'Spain'), ('LK', u'Sri Lanka'), ('SD', u'Sudan'), ('SR', u'Suriname'), 
	('SZ', u'Swaziland'), ('SE', u'Sweden'), 
	('CH', u'Switzerland'), ('SY', u'Syrian Arab Republic'), ('TH', u'Thailand'), 
	('TL', u'Timor-leste'), ('TG', u'Togo'), 
	('TT', u'Trinidad and Tobago'), 
	('TN', u'Tunisia'), ('TR', u'Turkey'), ('TM', u'Turkmenistan'), 
	('UG', u'Uganda'), ('UA', u'Ukraine'), ('UN', u'UNHCR'), ('AE', u'United Arab Emirates'), 
	('GB', u'United Kingdom'), ('TZ', u'United Republic of Tanzania'), 
	('US', u'United States of America'), ('UY', u'Uruguay'), ('UZ', u'Uzbekistan'), 
	('VU', u'Vanuatu'), 
	('VE', u'Venezuela, Bolivarian Republic of'), ('VN', u'Viet Nam'), 
	('YE', u'Yemen'), 
	('ZM', u'Zambia'), ('ZW', u'Zimbabwe'),
        )
    ),
    ('Characters', (
        ('Charles de Salaberry', u'Charles de Salaberry'),
        )
    ),
)

ASSIGN_TYPE = (( True, 'Country'), (False, 'Character'))

